<div class="relative min-h-screen w-full flex items-center justify-center p-4 sm:p-6 lg:p-8">
    <div class="absolute inset-0 z-0">
        <img alt="Aerial view of a city in Anambra" class="h-full w-full object-cover blur-sm"
            src="https://lh3.googleusercontent.com/aida-public/AB6AXuAvwlVhyt2UbEBfP6VMV3Gjq9IJfMdCEG27imFtsRWFaBKpRJkKO2fMBm6D2kUXMk9v4P57g_o1EhCq7hKcNkLUVf_5WNPKM4Eq2PSNkkLlT-V534G52fn_7ZYFX3OYm01jFs5UZwNJjNyJ7CNnAuEKuWoYNUIkpjn6cO2v8yaxykAjNPLIsHuaXWIJVpA4af_RqWg79yNUm2EvDwl8or2KKKigNSKrkuoq1K_sDwdK9u-QteZditUNjceGl20UBS9OZzPvcVlAKpX5" />
        <div class="absolute inset-0 bg-black/50"></div>
    </div>
    <div
        class="relative z-10 w-full max-w-7xl rounded-2xl bg-black/40 backdrop-blur-lg p-6 sm:p-8 md:p-12 text-white shadow-2xl">


        <header class="flex flex-col sm:flex-row justify-between items-center mb-8">
            <img src="{{asset('img_1.png')}}">
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <map name="image-map">
                <area target="" alt="Ayamelum" title="Ayamelum" href="http://ayamelum"
                    coords="619,8,581,41,570,92,551,130,527,202,488,244,465,329,566,288,598,258,623,320,651,350,673,328,757,291,792,233,803,129,888,107,951,53,969,11"
                    shape="poly">
                <area target="" alt="Anambra East" title="Anambra East" href="http://anambra.east"
                    coords="595,278,451,347,426,427,368,471,332,530,280,576,279,662,366,676,372,627,436,561,480,522,535,501,638,481,647,426,625,388,651,363,621,341"
                    shape="poly">
                <area target="" alt="Oyi" title="Oyi" href="http://oyi"
                    coords="639,493,547,505,514,525,478,531,376,643,373,733,383,745,554,696,600,651" shape="poly">
                <area target="" alt="Derukota" title="Derukota" href="http://derukota"
                    coords="648,490,627,570,606,651,563,702,571,708,627,663,721,606,711,554" shape="poly">
                <area target="" alt="Awka North" title="Awka North" href="http://awka.north"
                    coords="762,302,664,358,632,386,654,418,648,482,717,547,725,600,794,596,824,575,883,589,972,619,977,567,976,548,1023,529,994,512,971,454,933,391,887,339"
                    shape="poly">
                <area target="" alt="Awka South" title="Awka South" href="http://awka.south"
                    coords="743,614,804,601,839,588,906,608,978,630,994,669,990,691,1003,708,951,763,906,802,858,811,820,784,781,758,782,702"
                    shape="poly">
                <area target="" alt="Nijikoka" title="Nijikoka" href="http://nijikoka"
                    coords="723,611,577,713,614,732,639,766,665,786,708,789,729,774,733,747,772,742,773,690,741,636,738,617"
                    shape="poly">
                <area target="" alt="Onisha North" title="Onisha North" href="http://onisha.north"
                    coords="246,702,284,680,366,687,367,735,373,747,370,769,324,795,321,811,308,811,294,786,232,780,226,771"
                    shape="poly">
                <area target="" alt="Beside Onisha North" title="Beside Onisha North" href="http://beside_onisha"
                    coords="221,779,180,859,264,866,274,825,289,795" shape="poly">
                <area target="" alt="Ogbaru" title="Ogbaru" href="http://ogbaru"
                    coords="182,875,267,875,331,1025,325,1043,353,1082,323,1148,272,1185,291,1313,273,1351,12,1351,30,1337,38,1293,39,1236,112,1145,146,1060,167,1007,160,924"
                    shape="poly">
                <area target="" alt="Idemili North" title="Idemili North" href="http://idemili.north"
                    coords="383,754,556,703,577,721,626,752,659,796,665,827,530,839,512,827,464,828,328,810,336,796,376,778"
                    shape="poly">
                <area target="" alt="Idemili South" title="Idemili South" href="http://idemili.south"
                    coords="294,797,286,825,271,849,275,871,322,906,382,916,445,901,502,869,579,943,628,950,663,848,663,836,531,844,508,834,461,836,329,816,302,818"
                    shape="poly">
                <area target="" alt="Anambra West" title="Anambra West" href="http://anambra.west"
                    coords="87,129,170,136,252,107,321,98,361,80,374,48,380,9,609,4,576,36,566,81,543,84,521,118,544,132,540,143,531,145,520,198,497,206,481,231,474,284,448,329,433,367,435,392,410,421,360,462,323,525,280,554,270,576,262,612,275,674,243,694,221,642,196,602,188,539,180,474,177,427,142,327,145,249,137,207"
                    shape="poly">
                <area target="" alt="Ihiala" title="Ihiala" href="http://ihiala"
                    coords="354,1089,324,1154,279,1191,297,1311,281,1354,431,1352,449,1294,671,1185,668,1163,604,1146,474,1117,478,1157,455,1167,405,1135"
                    shape="poly">
                <area target="" alt="Orumba North" title="Orumba North" href="http:/orumba.north"
                    coords="996,658,1001,678,997,694,1010,709,959,770,909,811,860,820,797,892,905,919,952,986,1063,938,1226,930,1211,898,1215,874,1190,840,1145,808,1128,777,1134,738,1139,719,1104,687,1079,646,1057,661"
                    shape="poly">
                <area target="" alt="Orumba South" title="Orunmba SOuth" href="http:/orumba.south"
                    coords="1340,989,1302,955,1257,944,1235,935,1069,942,956,994,985,1056,1003,1091,1023,1116,1054,1120,1092,1142,1105,1140,1145,1140,1190,1153,1190,1087,1197,1046,1229,1011,1302,999"
                    shape="poly">
                <area target="" alt="Nnewi South" title="Nnewi South" href="http://nnewi.south"
                    coords="501,877,449,905,451,941,435,1008,442,1070,469,1103,538,1055,583,992,601,956,579,950"
                    shape="poly">
                <area target="" alt="Aguta" title="Aguta" href="http://aguta"
                    coords="793,900,901,925,949,990,988,1074,1020,1123,1048,1131,1088,1150,1102,1150,1077,1177,1053,1184,956,1144,868,1113,826,1108,803,1110,819,1062,779,1028,681,995,665,966,689,963,708,942,743,937"
                    shape="poly">
                <area target="" alt="Nnewi South" title="Nnewi South" href="http://nnewi.south2"
                    coords="606,956,563,1039,475,1103,577,1133,604,1140,670,1152,791,1113,811,1060,756,1030,681,1001,657,968"
                    shape="poly">
                <area target="" alt="Beside Awka South" title="Beside Awka South" href="http://beside.awka.south"
                    coords="665,797,671,830,670,844,648,900,634,952,659,960,684,954,698,937,740,929,788,893,849,818,817,788,776,766,773,752,737,759,734,779,715,797"
                    shape="poly">
                <area target="" alt="Beside Udemili South" title="Beside Udemili South"
                    href="http://beside.udemili.south"
                    coords="277,885,311,907,375,925,439,910,443,937,432,996,431,1050,444,1085,464,1106,473,1152,455,1159,402,1127,357,1084,332,1042,337,1028"
                    shape="poly">
            </map>

        </header>
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div class="flex flex-col justify-between">
                <div class="map-container">
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img src="{{asset('img.png')}}" usemap="#image-map" id="anambra-map">
                    <!-- Call-to-action elements -->
                    <div class="map-cta-overlay"></div>
                    <div class="map-instruction">Click on any area to explore</div>
                    <div class="map-border-glow"></div>
                    <!-- Interactive overlays -->
                    <div class="map-overlay">
                        <div class="area-hover-overlay" id="hover-overlay"></div>
                        <div class="area-selected-overlay" id="selected-overlay"></div>
                    </div>

                    <map name="image-map">
                        <area target="" alt="Ayamelum" title="Ayamelum" href="http://ayamelum"
                            coords="619,8,581,41,570,92,551,130,527,202,488,244,465,329,566,288,598,258,623,320,651,350,673,328,757,291,792,233,803,129,888,107,951,53,969,11"
                            shape="poly">
                        <area target="" alt="Anambra East" title="Anambra East" href="http://anambra.east"
                            coords="595,278,451,347,426,427,368,471,332,530,280,576,279,662,366,676,372,627,436,561,480,522,535,501,638,481,647,426,625,388,651,363,621,341"
                            shape="poly">
                        <area target="" alt="Oyi" title="Oyi" href="http://oyi"
                            coords="639,493,547,505,514,525,478,531,376,643,373,733,383,745,554,696,600,651"
                            shape="poly">
                        <area target="" alt="Derukota" title="Derukota" href="http://derukota"
                            coords="648,490,627,570,606,651,563,702,571,708,627,663,721,606,711,554" shape="poly">
                        <area target="" alt="Awka North" title="Awka North" href="http://awka.north"
                            coords="762,302,664,358,632,386,654,418,648,482,717,547,725,600,794,596,824,575,883,589,972,619,977,567,976,548,1023,529,994,512,971,454,933,391,887,339"
                            shape="poly">
                        <area target="" alt="Awka South" title="Awka South" href="http://awka.south"
                            coords="743,614,804,601,839,588,906,608,978,630,994,669,990,691,1003,708,951,763,906,802,858,811,820,784,781,758,782,702"
                            shape="poly">
                        <area target="" alt="Nijikoka" title="Nijikoka" href="http://nijikoka"
                            coords="723,611,577,713,614,732,639,766,665,786,708,789,729,774,733,747,772,742,773,690,741,636,738,617"
                            shape="poly">
                        <area target="" alt="Onisha North" title="Onisha North" href="http://onisha.north"
                            coords="246,702,284,680,366,687,367,735,373,747,370,769,324,795,321,811,308,811,294,786,232,780,226,771"
                            shape="poly">
                        <area target="" alt="Beside Onisha North" title="Beside Onisha North"
                            href="http://beside_onisha" coords="221,779,180,859,264,866,274,825,289,795" shape="poly">
                        <area target="" alt="Ogbaru" title="Ogbaru" href="http://ogbaru"
                            coords="182,875,267,875,331,1025,325,1043,353,1082,323,1148,272,1185,291,1313,273,1351,12,1351,30,1337,38,1293,39,1236,112,1145,146,1060,167,1007,160,924"
                            shape="poly">
                        <area target="" alt="Idemili North" title="Idemili North" href="http://idemili.north"
                            coords="383,754,556,703,577,721,626,752,659,796,665,827,530,839,512,827,464,828,328,810,336,796,376,778"
                            shape="poly">
                        <area target="" alt="Idemili South" title="Idemili South" href="http://idemili.south"
                            coords="294,797,286,825,271,849,275,871,322,906,382,916,445,901,502,869,579,943,628,950,663,848,663,836,531,844,508,834,461,836,329,816,302,818"
                            shape="poly">
                        <area target="" alt="Anambra West" title="Anambra West" href="http://anambra.west"
                            coords="87,129,170,136,252,107,321,98,361,80,374,48,380,9,609,4,576,36,566,81,543,84,521,118,544,132,540,143,531,145,520,198,497,206,481,231,474,284,448,329,433,367,435,392,410,421,360,462,323,525,280,554,270,576,262,612,275,674,243,694,221,642,196,602,188,539,180,474,177,427,142,327,145,249,137,207"
                            shape="poly">
                        <area target="" alt="Ihiala" title="Ihiala" href="http://ihiala"
                            coords="354,1089,324,1154,279,1191,297,1311,281,1354,431,1352,449,1294,671,1185,668,1163,604,1146,474,1117,478,1157,455,1167,405,1135"
                            shape="poly">
                        <area target="" alt="Orumba North" title="Orumba North" href="http://orumba.north"
                            coords="996,658,1001,678,997,694,1010,709,959,770,909,811,860,820,797,892,905,919,952,986,1063,938,1226,930,1211,898,1215,874,1190,840,1145,808,1128,777,1134,738,1139,719,1104,687,1079,646,1057,661"
                            shape="poly">
                        <area target="" alt="Orumba South" title="Orumba South" href="http://orumba.south"
                            coords="1340,989,1302,955,1257,944,1235,935,1069,942,956,994,985,1056,1003,1091,1023,1116,1054,1120,1092,1142,1105,1140,1145,1140,1190,1153,1190,1087,1197,1046,1229,1011,1302,999"
                            shape="poly">
                        <area target="" alt="Nnewi South" title="Nnewi South" href="http://nnewi.south"
                            coords="501,877,449,905,451,941,435,1008,442,1070,469,1103,538,1055,583,992,601,956,579,950"
                            shape="poly">
                        <area target="" alt="Aguta" title="Aguta" href="http://aguta"
                            coords="793,900,901,925,949,990,988,1074,1020,1123,1048,1131,1088,1150,1102,1150,1077,1177,1053,1184,956,1144,868,1113,826,1108,803,1110,819,1062,779,1028,681,995,665,966,689,963,708,942,743,937"
                            shape="poly">
                        <area target="" alt="Nnewi South" title="Nnewi South" href="http://nnewi.south2"
                            coords="606,956,563,1039,475,1103,577,1133,604,1140,670,1152,791,1113,811,1060,756,1030,681,1001,657,968"
                            shape="poly">
                        <area target="" alt="Beside Awka South" title="Beside Awka South"
                            href="http://beside.awka.south"
                            coords="665,797,671,830,670,844,648,900,634,952,659,960,684,954,698,937,740,929,788,893,849,818,817,788,776,766,773,752,737,759,734,779,715,797"
                            shape="poly">
                        <area target="" alt="Beside Udemili South" title="Beside Udemili South"
                            href="http://beside.udemili.south"
                            coords="277,885,311,907,375,925,439,910,443,937,432,996,431,1050,444,1085,464,1106,473,1152,455,1159,402,1127,357,1084,332,1042,337,1028"
                            shape="poly">
                    </map>
                </div>
                <div class="mt-8 text-center lg:text-left">
                    <h2 class="text-3xl font-semibold text-white/90">Tap below to learn more about Anambra</h2>
                    <a class="mt-6 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-bold text-gray-900 shadow-lg transition-transform hover:scale-105"
                        href="{{ route('about') }}" wire:navigate>
                        About Anambra
                        <span class="material-icons-outlined">arrow_forward</span>
                    </a>
                </div>
            </div>
            <div class="area-description rounded-xl bg-white/10 p-6 sm:p-8 backdrop-blur-sm border border-white/20">
                <h3 class="text-3xl font-bold text-white mb-4">Anambra West</h3>
                <div class="space-y-4 text-white/80">
                    <p>
                        {{-- Anambra West is a Local Government Area in Anambra State, Nigeria. It is located in the
                        western part of the state and is known for its agricultural activities and riverine communities
                        along the Niger River.--}}
                    </p>
                    <p class="text-sm text-white/60 italic">
                        Click on any area of the map above to learn more about different local government areas in
                        Anambra State.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    // Area descriptions data
    const areaDescriptions = {
        'ayamelum': {
            title: 'Ayamelum',
            description: `Ayamelum is a local government area (LGA) in Anambra state, in the southeastern part of Nigeria with headquarters in Anaku. Ayamelum’s area is situated at the border between Enugu state and Anambra state. The communities in the area are notable for food production. Ayamelum falls under the Anambra Central senatorial district in Anambra State, Nigeria. As at the 2006 census, this LGA has a total population of 158,152 people.

Overview
Anambra state, which is located in Nigeria's Southeast geopolitical zone, has the Ayamelum local government area. There are several towns and villages in the area, including Umueje, Igbakwu, Anaku, Umuerum, Ifite, Ogwari, Omasi, and Umumbo, where the LGA's administrative center is located. The Igbo ethnic group is the dominant tribe in the Ayamelum LGA, and both the Igbo and English languages are widely used there. According to estimates, there are 121,855 people living in the Ayamelum LGA, and the majority of them identify as Christians. The Ofalla, Obubezi, and Olila aka festivals are only a few of the prominent and indigenous celebrations held in Ayamelum LGA.

Economy
Ayamelum LGA residents depend heavily on agriculture for their livelihoods, with a significant portion of the population engaged in both subsistence and commercial farming. In Ayamelum, crops like yams, cassava, cocoyams, and various vegetables are farmed.

Climate
The climate of Ayamelum is tropical humid with wet and dry seasons and annual rainfall between 1300-3000mm. These areas are characterized by high temperatures, rainfall, and humidity.`
        },
        'anambra-east': {
            title: 'Anambra East',
            description: `Anambra East is a Local Government Area in Anambra State, south-central Nigeria. It has its headquarters in Otuocha. Towns that make up the local government are Aguleri, Enugwu Aguleri, Eziagulu Otu Aguleri, Enugwu Otu Aguleri, Mkpunando-otu Aguleri, Ikem Ivite, Igbariam, Umuoba Anam, Nando, Umueri, and Nsugbe. It is part of the Greater Onitsha Metropolis. Anambra East falls under the Anambra Central senatorial district of Anambra state. As at the 2006 census, this LGA has a total population of 152,149 people.

In Anambra East, oil and gas were discovered in large quantities on the bank of Aguleri town and the president has commissioned exploration on the site and the operational head office of Orient Petroleum and Housing estate is about to be sited in Aguleri by the Orient Petroleum Resources.

Currently, Anambra East local government area recorded history with the successful landing and take-off of the Embraer ERJ 145 jet operated by Air Peace. Anambra State government signed a two billion dollar Memorandum of Understanding with Orient Petroleum Resources and Elite International Investment Limited for the building of an international airport city in Umueri, Anambra East Local Government Area.

Economy
Yam, rice, cassava, and cocoyam are the main crops grown in the Anambra east LGA, which is both commercial and agricultural. Markets including the Otuocha market, the New parts market, and the Afia Ama market contribute significantly to the area's economic reputation. With significant crude oil deposits discovered in Aguleri town, Anambra East is also endowed with abundant mineral resources.

Climate
Anambra East LGA's average temperature is 27.5°C, with a humidity of 79%. The region has two significant seasons: the dry season, which runs from November to March, and the rainy season, which lasts from April to October.`
        },
        'oyi': {
            title: 'Oyi',
            description: `Oyi is a Local Government Area in Anambra State, Nigeria. It is home to the Oyi people. The towns that make up the local government are Nkwelle Ezunaka, Awkuzu, Ogbunike, Umunede Umunya and Nteje. This LGA falls under the Anambra Central senatorial district. Oyi/Ayamelum is a Federal Constituency represented by Hon Chinedu Eluemuno at the Federal House of Representatives, Abuja. It is part of the Greater Onitsha Metropolis.

Demography
Oyi LGA's administrative center is in the town of Nteje. Numerous towns and villages, including Ogbunike, Umuneba, Umunya, Nteje, Nkwelle, and Awkuzu, are part of the LGA. Oyi LGA is now expected to have 249,448 residents, with Igbo people making up the majority of the local population. In the LGA, the Igbo language is widely spoken, and Christianity is a very popular religion there. Oyi LGA has a number of vibrant festivals, such as the Ofala and Isigwu festivals, and the area is home to the well-known Ogbunike Caves, a UNESCO World Heritage Site. As at the 2006 census, this LGA has a total population of 168,201 people.

Economy
The Modern Aluminium market in Ogbunike is one of the several markets in the Oyi LGA, which serves as a major trading center. With products including rice, yams, cassava, and breadfruit cultivated nearby, agriculture plays a significant economic role in Oyi LGA. The LGA is also well-known for its commercial fishing, farming, and hunting operations.

Climate
The climate in Oyi is tropical monsoon. Throughout the year the temperatures are high and there is a lot of rainfall.`
        },
        'awka-north': {
            title: 'Awka North',
            description: `Awka North is a Local Government Area in Anambra State, south-central Nigeria. Towns that make up the local government are Awba Ofemili, Ugbenu, Ugbene, Ebenebe, Achalla (the capital), Urum, Amansea, Amanuke, Isu Aniocha, Mgbakwu. This LGA falls under the Anambra North senatorial district. The headquarters is at Achalla. As at the 2006 census, this LGA has a total population of 112,192 people.

Geography
The Awka North region experiences wet and dry seasons, with an estimated total precipitation of 2950 mm. The area's average temperature is 27 °C, with average humidity around 70%.

Climate
Awka North in the wet season is usually warm, unfriendly, and overcast and the dry season is hot, muggy, and sometimes cloudy.

Economy
Rice, yams, cassava, and maize are grown widely. Residents also engage in fishing in the area's numerous rivers and tributaries. Markets like Eke Awka and Aforigwe support trade.`
        },
        'awka-south': {
            title: 'Awka South',
            description: `Awka South Local Government Area (LGA) comprises nine towns: Amawbia, Awka, Ezinato, Isiagu, Mbaukwu, Nibo, Nise, Okpuno and Umuawulu. It is in the Anambra North senatorial district. As at the 2006 census, population is 189,654.

Awka is the seat of government with many prominent people. Amawbia hosts the Governor's Lodge and State Prisons. Nise hosts WAEC's state head office and St. Paul University College. Isiagu is notable for fertile farmlands and ancient heritage with current traditional ruler Igwe Augustine Nwankwo (Igwe Agu I of Isiagu).

Economy
Farming is the main source of income with yam, maize, cocoyam, and cassava cultivated in sizable amounts. Markets include Eke market in Nibo and Awka Capital Territory Modern Market in Isiagu.

Geography
Wet and dry seasons, ~2950 mm precipitation, average temperature ~27 °C, average humidity ~70%.`
        },
        'nijikoka': {
            title: 'Njikoka',
            description: `Njikoka is a Local Government Area in Anambra State, south-east Nigeria. Towns include Abagana, Abba, Enugwu-Agidi, Enugwu-ukwu, Nawfia and Nimo, with headquarters at Abagana. It falls under the Anambra North senatorial district. As at the 2006 census, population is 148,394.

Geography
Average temperature ~26 °C and humidity ~71%. Numerous rivers and tributaries with ~2600 mm of annual precipitation.

Economy
A thriving commerce industry including the Enugwu-Agidi International Timber Market. Crops include rice, yams, cocoyams, and cassava. The LGA hosts hotels, banks, businesses, and recreational areas.`
        },
        'onisha-north': {
            title: 'Onitsha North',
            description: `Onitsha North is a Local Government Area in Anambra State, Nigeria. Located in Anambra Central senatorial district, it is bordered by Ogbaru to the south, Idemili North and Oyi to the east, and Anambra East to the north. Population (2022 est.): 179,400.

Economy
Trade-driven; Main Market, Onitsha is situated here. Numerous banks, hotels, restaurants, and leisure spots contribute to the economy.

Climate
Average temperature ~26 °C. Two seasons with heavy and frequent rainfall. The River Niger flows through the LGA. Deforestation led to an average annual CO2 release of 557t (2001–2022).`
        },
        'ogbaru': {
            title: 'Ogbaru',
            description: `Ogbaru is a local government area with headquarters in Atani and part of the Greater Onitsha Metropolis. Bordered by parts of Rivers and Delta State, it includes Obeagwe, Oluta, Ochuche, Umunankwo, Okpoko, Odekpe, Atani, and Umuzu.

History
Ogbaru people are farmers and known historically as warriors; they share lineage and boundaries with Onitsha, Oguta (Imo), Anioma (Delta) and Ndoni (Rivers).

Economy
Hosts a Nigerian naval base, an industrial river harbor, and strategic roads including the Second Niger Bridge. Projected as a key link to the southeast and south zones.

Geography & Climate
The Niger River is central to Ogbaru’s territory. Frequent flooding during rainy seasons affects farms; major floods in 2018 and 2020 caused loss of life and displacement.`
        },
        'idemili-north': {
            title: 'Idemili North',
            description: `Idemili North is a Local Government Area in Anambra State, South-Central Nigeria. Towns include Abacha, Abatete, Eziowelle, Ideani, Nkpor, Obosi, Ogidi, Oraukwu, Uke, Umuoji. Headquarters: Ogidi. Part of the Greater Onitsha Metropolis. Population (2006): 431,005.

Economy
A center for trade with markets including Uke market and Building Materials market. Farming of yam, cassava, cocoyam, and vegetables; residents also engage in fishing, blacksmithing, and handicrafts.

Geography
Area ~390 sq km; River Idemili flows within. Average temperature ~25°C, humidity ~69%, wind ~11 km/h.`
        },
        'idemili-south': {
            title: 'Idemili South',
            description: `Idemili South is a Local Government Area in Anambra State, South-East Nigeria. Headquarters: Ojoto Secretariat. Towns: Akwu-Ukwu, Alor, Awka-Etiti, Ojoto, Nnokwa, Oba and Nnobi. Part of the Greater Onitsha Metropolis. Population (2006): 206,816.

Geography
River Idemili flows through its ~700 sq km territory. Average temperature ~25°C; rainy and dry seasons; humidity ~69%, wind ~11 km/h.

Economy
Farming (vegetables, cassava, yam, rice); markets such as Afor Nnobi and Ezeihulu; several hotels, banks, and institutions.`
        },
        'anambra-west': {
            title: 'Anambra West',
            description: `Anambra West is a Local Government Area in the northwestern part of Anambra State, Nigeria. Headquarters: Otuocha. Falls under the Anambra Central senatorial district. Population (2006): 167,303.

Geography
Average temperature ~27.5°C, humidity ~79%. Two seasons: dry (Nov–Mar) and rainy (Apr–Oct).

Economy
Significant resources with popular fishing. Crops include yam, cassava, corn, and vegetables. Trade thrives with markets like Eke Nnokwa and Owelle Central market.`
        },
        'ihiala': {
            title: 'Ihiala',
            description: `Ihiala is a city in Nigeria, located in the southern part of Anambra State and within Igboland. It is the administrative capital of Ihiala LGA. Population ~430,800. Towns include Amorka, Azia, Lilu, Okija, Mbosi, Isseke, Orsumoghu, Ubuluisuzor and Uli. Falls under Anambra South senatorial district.

Economy
Agriculture-focused with vegetables, cassava, yams, and cocoyams. Markets include Nkwor Ihiala and Nkwogbe. Hosts many banks, hotels, and institutions.

Boundaries
Borders Nnewi LGA (NW), IMO State (NE/E), Ekwusigo (W), and Delta State (S).

Climate
Rainy season is warm and overcast; dry season hot and partly cloudy (67–87°F typical).`
        },
        'orumba-north': {
            title: 'Orumba North',
            description: `Orumba North is a Local Government Area with administrative center at Ajali. Towns include Ndikelionwu, Okpeze, Nanka, Okoh, Omogho, Ufuma, Amaetiti, Awa, and Ndiokolo. Falls under Anambra South senatorial district. Estimated population: 253,120.

Economy
Hosts hotels, banks, industries, schools, and government establishments. Viable trade with markets such as Afor Udo Nanka and Nkwo Omogho. Other occupations include farming, animal rearing, and beauty treatment.

Geography
Two seasons (Mar–Oct rainy; Nov–Feb dry). Average temperature ~26°C.`
        },
        'orumba-south': {
            title: 'Orumba South',
            description: `Orumba South has headquarters in Umunze. Towns include Akpu, Umuomaku, Eziagu, Ezira, Ihite, Nkerehi (Umuchukwu), Nawfija, Ogboji, Ogbunka, Owerre-Ezukala, Agbudu, Onneh, Isulo, and Enugwu-Umuonyia. Falls under Anambra South senatorial district. Estimated population: 183,447.

Economy
Markets include Eke Isulo and Nkwo Ogbunka. Farming is significant with rice, yams, maize, and cassava. Hunting, fishing, and wood carving are also important.

Geography
Average temperature ~26°C; hosts several rivers and streams; distinct dry and rainy seasons; average humidity ~66%.`
        },
        'nnewi-south': {
            title: 'Nnewi South',
            description: `Nnewi South LGA in Anambra South Senatorial Zone has headquarters in Ukpor. Towns and villages include Ezinifite, Utuh, Ebenator, Osumenyi, Amichi, Unubi, Ekwulumili, Azigbo and Akwa-Ihedi. Population is estimated at 218,717. The Chairman is Hon. Van George Chinedu Ezeogidi (assumed office 2024).

Economy
Heavily industrialized with manufacturing businesses. Vibrant trade in Eke Amichi, Eke Osu and Abanitor markets. Numerous banks, hotels, hospitals, government and private organizations.

Geography
Many rivers and streams; average temperature ~26 °C; annual precipitation ~2550 mm; average humidity ~72%.`
        },
        'aguta': {
            title: 'Aguata',
            description: `Aguata is a Local Government Area in Anambra State, Nigeria, under the Anambra South senatorial district. A major part of its headquarters falls into the town of Aguluezechukwu, while a smaller part falls into Ekwulobia. Population: 286,897.

Economy
Subsistence farming is common. Eke and Nkwo marketplaces support trade. The LGA hosts hotels, microfinance banks, and other enterprises.

Ekwulobia
Largest town in Aguata (~100,000 people). Major commercial hub with branches of most Nigerian banks, a small stadium, a federal prison (partly in Ezinifite), and Eke Market. New agricultural factories attract workers. Major transit hub with daily transport to cities like Onitsha, Nnewi, Awka, Port Harcourt, Lagos, Abuja, Enugu, and Abakaliki.

Climate
Warm year-round. Dry season is muggy and partially cloudy; wet season is overcast. Average annual temperature ranges from 17–30°C.

Culture
The Awuka masquerade of Aguluezechukwu and Nkpokiti Ije Enu Dance are renowned for unique dance steps and have won accolades in Anambra State.`
        },
        'derukota': {
            title: 'Derukota',
            description: `Derukota (placeholder).`
        },
        'dunukofia': {
            title: 'Dunukofia',
            description: `Dunukofia is a Local Government Area in Anambra State, South-East Nigeria. Towns: Ukpo (HQ), Ifitedunu, Dunukofia Umunnachi, Umudioka, Ukwulu and Nawgu. Borders Awka North, Idemili North, Njikoka and Oyi LGAs. Falls under the Anambra North senatorial district. Population (2006): 96,517.

Geography
Two main seasons yearly. Average annual temperature ~28°C; average rainfall ~2950 mm.

Economy
Crops include yam, rice, cassava, and maize; farming is primary. Commerce is vibrant with markets like Afor Igwe market in Umudioka. Education and healthcare facilities are notable.`
        },
        'ekwusigo': {
            title: 'Ekwusigo',
            description: `Ekwusigo is a Local Government Area in Anambra State, south-central Nigeria. Towns: Ozubulu, Oraifite, Ichi and Ihembosi. Headquarters: Ozubulu. Population (2006): 158,429.

Geography
Two major seasons (dry and rainy), various rivers, average temperature ~26 °C, humidity ~85%, average wind speed ~13 km/h.

Economy & Culture
Cultivates maize, yams, cassava, and cocoyams. Markets include Ichi central market. Notable for manufacturing, welding, and fishing. Festivals include Uzoiyi and New Yam. The Nigerian Post Office in Ozubulu is a significant landmark.`
        },
        'nnewi-north': {
            title: 'Nnewi North',
            description: `Nnewi North is a Local Government Area where Nnewi is the only town and headquarters. It has four villages: Otolo, Uruagu, Umudim and Nnewi-ichi. Falls under the Anambra South senatorial district. Population (2006): 155,443.

Economy
Industrialized with many manufacturing businesses. Trade thrives at Nkwo Nnewi Main market. Numerous banks, hotels, rest areas, governmental organizations, and private businesses contribute to the economy.

Geography
Various rivers and streams; average temperature ~26°C; dry and wet seasons; average humidity ~72%; annual precipitation ~2550 mm.`
        },
        'onitsha-south': {
            title: 'Onitsha South',
            description: `Onitsha South LGA has headquarters in Fegge, Onitsha. Predominantly commercial with markets such as Ochanja that attract thousands of traders. Estimated population ~213,894. Neighborhoods include Modebe, Upper Iweka, Ojukwu Gateway, Arondizuogu Street, Port Harcourt Road, Zik Avenue, Ozomagala Road, and Niger Street. Notable sites: Christ the King College and Our Lady's High School.

Economy
Trade-driven with numerous markets and businesses including banks, hotels, restaurants, and leisure spots.

Geography
Average temperature ~26°C; heavy and frequent rainfall in the rainy season. Adjacent to River Niger; average humidity ~79%.`
        }
    };

    function updateAreaDescription(areaKey) {
        const area = areaDescriptions[areaKey];
        if (area) {
            const titleElement = document.querySelector('.area-description h3');
            const descriptionContainer = document.querySelector('.area-description .space-y-4');

            if (titleElement && descriptionContainer) {
                titleElement.textContent = area.title;
                // Convert double newlines to paragraphs and single newlines to <br>
                // Also bolden sub-headers like Economy, Climate, etc.
                const headerSet = new Set([
                    'overview',
                    'economy',
                    'climate',
                    'geography',
                    'history',
                    'demography',
                    'demographics',
                    'boundaries',
                    'population',
                    'transportation',
                    'economy & culture',
                    'geography & climate',
                    'ekwulobia',
                    'culture'
                ]);

                const paragraphs = area.description
                    .split(/\n{2,}/)
                    .map(chunk => {
                        // For each chunk, check if the first line is a header (case-insensitive, optional colon)
                        const lines = chunk.split(/\n/);
                        const firstLine = (lines[0] || '').trim();
                        const normalized = firstLine.replace(/:$/, '').trim().toLowerCase();

                        if (headerSet.has(normalized)) {
                            const body = lines.slice(1).join('\n').trim();
                            const headerHtml = `<p><strong>${firstLine.replace(/:$/, '')}</strong></p>`;
                            if (body.length > 0) {
                                return headerHtml + `<p>${body.replace(/\n/g, '<br>')}</p>`;
                            }
                            return headerHtml;
                        }

                        // If the whole chunk is exactly a header word alone
                        if (headerSet.has(chunk.trim().replace(/:$/, '').toLowerCase())) {
                            const plain = chunk.trim().replace(/:$/, '');
                            return `<p><strong>${plain}</strong></p>`;
                        }

                        return `<p>${chunk.replace(/\n/g, '<br>')}</p>`;
                    })
                    .join('');
                descriptionContainer.innerHTML = paragraphs;
            }
        }
    }

    // Global variables for tracking state
    let currentSelectedArea = null;
    let hoverOverlay = null;
    let selectedOverlay = null;

    // Function to calculate bounding box from polygon coordinates
    function getPolygonBounds(coords) {
        const points = coords.split(',').map(Number);
        let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;

        for (let i = 0; i < points.length; i += 2) {
            const x = points[i];
            const y = points[i + 1];
            minX = Math.min(minX, x);
            maxX = Math.max(maxX, x);
            minY = Math.min(minY, y);
            maxY = Math.max(maxY, y);
        }

        return { minX, minY, maxX, maxY, width: maxX - minX, height: maxY - minY };
    }

    // Function to create clip-path from polygon coordinates
    function createPolygonClipPath(coords, bounds) {
        const points = coords.split(',').map(Number);
        const clipPathPoints = [];

        for (let i = 0; i < points.length; i += 2) {
            const x = points[i];
            const y = points[i + 1];
            // Convert coordinates to percentage relative to bounding box
            const xPercent = ((x - bounds.minX) / bounds.width) * 100;
            const yPercent = ((y - bounds.minY) / bounds.height) * 100;
            clipPathPoints.push(`${xPercent}% ${yPercent}%`);
        }

        return `polygon(${clipPathPoints.join(', ')})`;
    }

    // Function to position overlay on area
    function positionOverlay(overlay, area, mapImg) {
        const coords = area.getAttribute('coords');
        const shape = area.getAttribute('shape');

        if (shape === 'poly' && coords) {
            const bounds = getPolygonBounds(coords);
            const mapRect = mapImg.getBoundingClientRect();
            const mapContainer = mapImg.parentElement;

            // Use the already scaled coordinates from imageMapResizer
            // The imageMapResizer library has already updated the coords to match the current image size
            // So we can use them directly without additional scaling
            overlay.style.left = bounds.minX + 'px';
            overlay.style.top = bounds.minY + 'px';
            overlay.style.width = bounds.width + 'px';
            overlay.style.height = bounds.height + 'px';

            // Create and apply the polygon clip-path to match the exact shape
            const clipPath = createPolygonClipPath(coords, bounds);
            overlay.style.clipPath = clipPath;
            overlay.style.webkitClipPath = clipPath; // For older browsers
        }
    }

    // Function to show hover effect
    function showHoverEffect(area) {
        if (!hoverOverlay) return;

        const mapImg = document.getElementById('anambra-map');
        if (mapImg && mapImg.complete) {
            positionOverlay(hoverOverlay, area, mapImg);
            hoverOverlay.classList.add('active');
        }
    }

    // Function to hide hover effect
    function hideHoverEffect() {
        if (hoverOverlay) {
            hoverOverlay.classList.remove('active');
        }
    }

    // Function to show selected effect
    function showSelectedEffect(area) {
        if (!selectedOverlay) return;

        // Remove previous selection
        if (currentSelectedArea) {
            selectedOverlay.classList.remove('active');
        }

        const mapImg = document.getElementById('anambra-map');
        if (mapImg && mapImg.complete) {
            positionOverlay(selectedOverlay, area, mapImg);
            selectedOverlay.classList.add('active');
            currentSelectedArea = area;
        }
    }

    function setupImageMapListeners() {
        // Get overlay elements
        hoverOverlay = document.getElementById('hover-overlay');
        selectedOverlay = document.getElementById('selected-overlay');

        const areas = document.querySelectorAll('area');
        const mapContainer = document.querySelector('.map-container');

        areas.forEach(area => {
            // Click handler
            area.addEventListener('click', function (e) {
                e.preventDefault();
                // Hide call-to-action effects after first interaction
                if (mapContainer) {
                    mapContainer.classList.add('interacted');
                }
                const alt = this.getAttribute('alt');
                const areaKey = alt.toLowerCase().replace(/\s+/g, '-');
                updateAreaDescription(areaKey);
                showSelectedEffect(this);
            });

            // Mouse enter handler
            area.addEventListener('mouseenter', function () {
                // Hide call-to-action effects on first hover too
                if (mapContainer && !mapContainer.classList.contains('interacted')) {
                    mapContainer.classList.add('interacted');
                }
                showHoverEffect(this);
            });

            // Mouse leave handler
            area.addEventListener('mouseleave', function () {
                hideHoverEffect();
            });
        });

        // Handle window resize to reposition overlays
        // Use a debounced approach to avoid excessive repositioning during resize
        let resizeTimeout;
        window.addEventListener('resize', function () {
            clearTimeout(resizeTimeout);
            resizeTimeout = setTimeout(function () {
                // Allow imageMapResize to update coordinates first
                setTimeout(function () {
                    if (currentSelectedArea && selectedOverlay) {
                        const mapImg = document.getElementById('anambra-map');
                        if (mapImg && mapImg.complete) {
                            positionOverlay(selectedOverlay, currentSelectedArea, mapImg);
                        }
                    }
                }, 50); // Small delay to ensure imageMapResize has finished
            }, 100);
        });
    }

    document.addEventListener('livewire:navigated', () => {
        imageMapResize();
        setupImageMapListeners();
    });

    // Handle initial load if needed, but livewire:navigated also fires on initial load
    // However, to be safe:
    if (document.readyState === 'complete' || document.readyState === 'interactive') {
        imageMapResize();
        setupImageMapListeners();
    } else {
        document.addEventListener('DOMContentLoaded', () => {
            imageMapResize();
            setupImageMapListeners();
        });
    }
</script>